/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-113328-g34a47b97de-20240115"
#endif /* AVUTIL_FFVERSION_H */
